[project]
name = "photoconvert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ttkbootstrap>=1.20.1",
    "wand>=0.6.13",
]
